import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('lexicon IPC surface', () => {
  it('exposes lexicon loading and saving through preload and main IPC', async () => {
    const preload = await readFile(new URL('../src/preload/index.ts', import.meta.url), 'utf8');
    const main = await readFile(new URL('../src/main/index.ts', import.meta.url), 'utf8');

    expect(preload).toContain('getLexicon(): Promise<Lexicon>');
    expect(preload).toContain('saveLexicon(lexicon: Lexicon): Promise<LexiconSaveResult>');
    expect(preload).toContain('getLexiconTextPaths(): Promise<Record<LexiconTextKind, string>>');
    expect(preload).toContain('getLexiconTextFiles(): Promise<LexiconTextFiles>');
    expect(preload).toContain('openLexiconTextFile(kind: LexiconTextKind)');
    expect(preload).toContain('importLexiconTextFiles(): Promise<LexiconSaveResult>');
    expect(preload).toContain('saveLexiconTextFiles(files: LexiconTextFiles): Promise<LexiconSaveResult>');
    expect(preload).toContain("ipcRenderer.invoke('v2t:get-lexicon')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:save-lexicon', lexicon)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:get-lexicon-text-paths')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:get-lexicon-text-files')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:open-lexicon-text-file', kind)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:import-lexicon-text-files')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:save-lexicon-text-files', files)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:copy-hotkey-diagnostics')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:repair-hotkey-helper')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:cleanup-stale-hotkey-helpers')");
    expect(preload).toContain('getPrompts(): Promise<PromptFiles>');
    expect(preload).toContain('savePrompt(mode: InputMode, content: string)');
    expect(preload).toContain('onAutoSyncStatus');
    expect(preload).toContain('refreshModelCatalog(): Promise<SetupPayload>');
    expect(preload).toContain('copyModelCatalogDiagnostics(): Promise<{ ok: true }>');
    expect(preload).toContain('testModelDownload(modelId: string): Promise<ModelDownloadProbeResult>');
    expect(preload).toContain('onModelCatalogRefresh');
    expect(preload).toContain('checkForUpdates(): Promise<AppUpdateState>');
    expect(preload).toContain('downloadUpdate(): Promise<AppUpdateState>');
    expect(preload).toContain('installUpdate(): Promise<AppUpdateState>');
    expect(preload).toContain('copyAppUpdateDiagnostics(): Promise<{ ok: true }>');
    expect(preload).toContain('openReleasePage(): Promise<{ ok: true }>');
    expect(preload).toContain('copySystemAudioDiagnostics(): Promise<{ ok: true }>');
    expect(preload).toContain('importModelArchive(modelId: string, filePath: string): Promise<InstallModelResult>');
    expect(preload).toContain('importModelDirectory(modelId: string, directoryPath: string): Promise<InstallModelResult>');
    expect(preload).toContain('clearModelInstall(modelId: string): Promise<InstallModelResult>');
    expect(preload).toContain('chooseModelRootPath(): Promise<PathActionResult>');
    expect(preload).toContain('chooseDataDir(): Promise<PathActionResult>');
    expect(preload).toContain('openPath(path: string): Promise<{ ok: boolean; error?: string }>');
    expect(preload).toContain('copyText(value: string): Promise<{ ok: true }>');
    expect(preload).toContain('getLlmInstallers(): Promise<LlmInstallerTarget[]>');
    expect(preload).toContain("openLlmInstaller(kind: LlmInstallerTarget['kind']): Promise<LlmInstallerActionResult>");
    expect(preload).toContain("openLlmInstallerDocs(kind: LlmInstallerTarget['kind']): Promise<LlmInstallerActionResult>");
    expect(preload).toContain('detectLlmProviders(): Promise<LlmProviderDetection[]>');
    expect(preload).toContain('enableLlmProvider(detection: LlmProviderDetection, model: string): Promise');
    expect(preload).toContain('testLlmConnection(): Promise<LlmTestResult>');
    expect(preload).toContain('chooseSyncRepoPath(): Promise');
    expect(preload).toContain('resolveSyncImport(strategy: SyncImportStrategy): Promise<SyncActionResult>');
    expect(preload).toContain('listConflictBackups(): Promise<string[]>');
    expect(preload).toContain('copyProcessingDiagnostics(): Promise<{ ok: true }>');
    expect(preload).toContain('onAppUpdateStatus');
    expect(preload).toContain("ipcRenderer.invoke('v2t:sync-all')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:refresh-model-catalog')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:copy-model-catalog-diagnostics')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:test-model-download', modelId)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:check-for-updates')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:download-update')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:install-update')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:copy-app-update-diagnostics')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:open-release-page')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:copy-system-audio-diagnostics')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:import-model-archive', modelId, filePath)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:import-model-directory', modelId, directoryPath)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:clear-model-install', modelId)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:choose-model-root-path')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:choose-data-dir')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:set-fallback-openai-key', value)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:get-llm-installers')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:open-llm-installer', kind)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:open-llm-installer-docs', kind)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:detect-llm-providers')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:enable-llm-provider', detection, model)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:test-llm-connection')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:choose-sync-repo-path')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:resolve-sync-import', strategy)");
    expect(preload).toContain("ipcRenderer.invoke('v2t:list-conflict-backups')");
    expect(preload).toContain("ipcRenderer.invoke('v2t:copy-processing-diagnostics')");
    expect(main).toContain("ipcMain.handle('v2t:get-lexicon'");
    expect(main).toContain("ipcMain.handle('v2t:save-lexicon'");
    expect(main).toContain("ipcMain.handle('v2t:get-lexicon-text-paths'");
    expect(main).toContain("ipcMain.handle('v2t:get-lexicon-text-files'");
    expect(main).toContain("ipcMain.handle('v2t:open-lexicon-text-file'");
    expect(main).toContain("ipcMain.handle('v2t:import-lexicon-text-files'");
    expect(main).toContain("ipcMain.handle('v2t:save-lexicon-text-files'");
    expect(main).toContain("ipcMain.handle('v2t:copy-hotkey-diagnostics'");
    expect(main).toContain("ipcMain.handle('v2t:repair-hotkey-helper'");
    expect(main).toContain("ipcMain.handle('v2t:cleanup-stale-hotkey-helpers'");
    expect(main).toContain("ipcMain.handle('v2t:get-prompts'");
    expect(main).toContain("ipcMain.handle('v2t:save-prompt'");
    expect(main).toContain("ipcMain.handle('v2t:sync-all'");
    expect(main).toContain("ipcMain.handle('v2t:refresh-model-catalog'");
    expect(main).toContain("ipcMain.handle('v2t:copy-model-catalog-diagnostics'");
    expect(main).toContain("ipcMain.handle('v2t:test-model-download'");
    expect(main).toContain("ipcMain.handle('v2t:check-for-updates'");
    expect(main).toContain("ipcMain.handle('v2t:download-update'");
    expect(main).toContain("ipcMain.handle('v2t:install-update'");
    expect(main).toContain("ipcMain.handle('v2t:copy-app-update-diagnostics'");
    expect(main).toContain("ipcMain.handle('v2t:open-release-page'");
    expect(main).toContain("ipcMain.handle('v2t:copy-system-audio-diagnostics'");
    expect(main).toContain("ipcMain.handle('v2t:reinstall-model'");
    expect(main).toContain("ipcMain.handle('v2t:cancel-model-install'");
    expect(main).toContain("ipcMain.handle('v2t:import-model-archive'");
    expect(main).toContain("ipcMain.handle('v2t:import-model-directory'");
    expect(main).toContain("ipcMain.handle('v2t:clear-model-install'");
    expect(main).toContain("ipcMain.handle('v2t:choose-model-root-path'");
    expect(main).toContain("ipcMain.handle('v2t:choose-data-dir'");
    expect(main).toContain("ipcMain.handle('v2t:set-fallback-openai-key'");
    expect(main).toContain("ipcMain.handle('v2t:open-path'");
    expect(main).toContain("ipcMain.handle('v2t:copy-text'");
    expect(main).toContain("ipcMain.handle('v2t:get-llm-installers'");
    expect(main).toContain("ipcMain.handle('v2t:open-llm-installer'");
    expect(main).toContain("ipcMain.handle('v2t:open-llm-installer-docs'");
    expect(main).toContain("ipcMain.handle('v2t:detect-llm-providers'");
    expect(main).toContain("ipcMain.handle('v2t:enable-llm-provider'");
    expect(main).toContain("ipcMain.handle('v2t:test-llm-connection'");
    expect(main).toContain("ipcMain.handle('v2t:choose-sync-repo-path'");
    expect(main).toContain("ipcMain.handle('v2t:resolve-sync-import'");
    expect(main).toContain("ipcMain.handle('v2t:list-conflict-backups'");
    expect(main).toContain("ipcMain.handle('v2t:copy-processing-diagnostics'");
    expect(main).toContain("scheduleAutoSync('voice-input')");
    expect(main).toContain('store.saveLexicon');
  });
});
