import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('settings navigation structure', () => {
  it('defines the fixed app pages used by the sidebar navigation', async () => {
    const app = await readFile(new URL('../src/renderer/App.tsx', import.meta.url), 'utf8');

    expect(app).toContain("type AppPage = 'voice' | 'asrModels' | 'llmModels' | 'statistics' | 'hotkey' | 'lexicon' | 'prompts' | 'sync' | 'advanced' | 'app'");
    expect(app).not.toContain("{ id: 'models', label: '模型' }");
    for (const label of ['语音输入', '语音识别模型', '文本整理模型', '统计', '快捷键', '词库', '提示词', 'GitHub 同步', '高级设置', '应用']) {
      expect(app).toContain(label);
    }
    expect(app).not.toContain('触发按键');
    expect(app).toContain('className="page-nav"');
    expect(app).toContain('className="page-content"');
    expect(app).toContain('复制诊断信息');
    expect(app).toContain('检查监听组件');
    expect(app).toContain('清理旧监听进程');
    expect(app).toContain('单击快捷键');
    expect(app).toContain('双击快捷键');
    expect(app).toContain('推荐分');
    expect(app).toContain('公开榜单');
    expect(app).toContain('官方评测');
    expect(app).toContain('V2T 适配分');
    expect(app).toContain('同步文字历史');
    expect(app).toContain('自动同步');
    expect(app).toContain('一键同步');
    expect(app).toContain('选择本地同步仓库位置');
    expect(app).toContain('使用本机覆盖远端');
    expect(app).toContain('导入远端到本机');
    expect(app).toContain('智能合并');
    expect(app).toContain('查看冲突备份');
    expect(app).toContain('上次长语音处理异常退出');
    expect(app).toContain('自然输入 Prompt');
    expect(app).toContain('结构输入 Prompt');
    expect(app).toContain('外观');
    expect(app).toContain('跟随系统');
    expect(app).toContain('浅色');
    expect(app).toContain('深色');
    expect(app).toContain('复制更新诊断');
    expect(app).toContain('更新包签名不匹配');
    expect(app).toContain('下载新版');
    expect(app).toContain('manualUpdateDownload ? null');
    expect(app).toContain('导入模型');
    expect(app).toContain('导入压缩包');
    expect(app).toContain('导入已解压目录');
    expect(app).toContain('清除残留');
    expect(app).toContain('当前一键下载主要来自 GitHub/k2-fsa Release');
    expect(app).toContain('待接入 / 外部服务');
    expect(app).toContain('只有满足以下条件的模型才显示“一键安装”');
    expect(app).toContain('AsrModelTable');
    expect(app).not.toContain('中文推荐分');
    expect(app).toContain('V2T 适配分');
    expect(app).toContain('公开中文指标');
    expect(app).toContain('资源占用');
    expect(app).toContain('英文公开榜参考');
    expect(app).toContain('刷新模型榜单');
    expect(app).toContain('复制榜单诊断');
    expect(app).toContain('下载测速');
    expect(app).not.toContain('本机测速');
    expect(app).not.toContain('本机速度');
    expect(app).toContain('输出测速');
    expect(app).toContain('输出速度');
    expect(app).toContain('批量输出测速');
    expect(app).toContain('cancelAsrBenchmark');
    expect(app).toContain('ASR 模型统一管理');
    expect(app).toContain('旧记录：未记录模型');
    expect(app).toContain('总录音时长');
    expect(app).toContain('ASR 模型使用情况');
    expect(app).toContain('getUsageStatistics');
    expect(app).toContain('copyAsrDiagnostics');
    expect(app).toContain('getCloudLlmModels');
    expect(app).toContain('refreshCloudLlmModels');
    expect(app).toContain('setOpenAtLogin');
    expect(app).toContain('openModelDownloadUrl');
    expect(app).toContain('copyModelDownloadUrl');
    expect(app).toContain('外部下载');
    expect(app).toContain('复制链接');
    expect(app).toContain('包体管理');
    expect(app).toContain('豆包 / 火山引擎');
    expect(app).toContain('低延迟流式');
    expect(app).toContain('云端高可用');
    expect(app).toContain('stats/usage-summary.json');
    expect(app).toContain('开机自动启动 V2T');
    expect(app).toContain('Performance');
    expect(app).toContain('发布时间');
    expect(app).toContain('只看免费');
    expect(app).toContain('只看推荐');
    expect(app).toContain('CloudModelTable');
    expect(app).toContain('CloudTestResultPanel');
    expect(app).toContain('Qwen 3.6 Plus 是付费稳定主力');
    expect(app).toContain('Ling-2.6-flash free 是免费快速候选');
    expect(app).toContain('已隐藏');
    expect(app).toContain('显示全部推荐');
    expect(app).toContain('测试已选模型');
    expect(app).toContain('词库试运行');
    expect(app).toContain('复制词库诊断');
    expect(app).toContain('TXT 文件编辑器');
    expect(app).toContain('重新从磁盘读取');
    expect(app).toContain('saveLexiconTextFiles');
    expect(app).toContain('lexicon.json 会作为运行时权威数据');
    expect(app).toContain('专有名词 terms.txt');
    expect(app).toContain('固定替换 replacements.txt');
    expect(app).toContain('禁用词 blocked.txt');
    expect(app).not.toContain('加入专有名词');
    expect(app).not.toContain('加入固定替换');
    expect(app).not.toContain('加入禁用词');
    expect(app).not.toContain('暂无专有名词');
    expect(app).not.toContain('暂无固定替换');
    expect(app).not.toContain('暂无禁用词');
    expect(app).toContain('录音上限');
    expect(app).toContain('开机时静默进入菜单栏');
    expect(app).not.toContain('MAX_RECORDING_MS');
    expect(app).toContain('录音时临时静音系统输出');
    expect(app).toContain('复制静音诊断');
    expect(app).toContain('muteSystemAudioForRecording');
    expect(app).toContain('restoreSystemAudioAfterRecording');
    expect(app).toContain('copySystemAudioDiagnostics');
    expect(app).toContain('应用版本');
    expect(app).toContain('构建号');
    expect(app).toContain('Release 标签');
    expect(app).not.toContain('v{setup.appInfo.version} · {setup.appInfo.buildCommit}');
    expect(app).not.toContain('当前版本 v{setup.appInfo.version} · {setup.appInfo.buildCommit}');
    expect(app).toContain('cloudSortDirection');
    expect(app).toContain('按发布时间倒序');
    expect(app).toContain('cloudLlmTags');
    expect(app).toContain('未找到同时满足当前筛选的模型');
    expect(app).toContain('放宽为只看免费');
    expect(app).toContain('放宽为只看推荐');
    expect(app).toContain('打开 OpenRouter API Key');
    expect(app).toContain('测试云端整理');
    expect(app).toContain('低内存本地模型建议');
    expect(app).toContain('重新测速');
    expect(app).toContain('结构化引擎');
    expect(app).toContain('本地规则');
    expect(app).toContain('Prompt 仅在启用 LLM 后生效');
    expect(app).toContain('语音识别模型 ASR');
    expect(app).toContain('ASR 负责把语音转成原始文字');
    expect(app).toContain('文本整理模型 LLM');
    expect(app).toContain('LLM 负责自然输入纠错和结构输入整理');
    expect(app).toContain('本地 LLM 安装向导');
    expect(app).toContain('当前整理引擎');
    expect(app).toContain('本地 LLM');
    expect(app).toContain('云端模型');
    expect(app).toContain('本地优先，云端兜底');
    expect(app).toContain('本地 OpenAI-compatible 配置');
    expect(app).toContain('云端 OpenAI-compatible 配置');
    expect(app).toContain('推荐云端模型');
    expect(app).toContain('OpenRouter Free Router');
    expect(app).toContain('openrouter/free');
    expect(app).toContain('Qwen Plus / DashScope');
    expect(app).toContain('快速模式：限制输出长度');
    expect(app).toContain('云端兜底');
    expect(app).toContain('Cloud Base URL');
    expect(app).toContain('官方文档');
    expect(app).toContain('路径管理');
    expect(app).toContain('模型目录');
    expect(app).toContain('同步数据目录');
    expect(app).not.toContain('title="GitHub 本地同步仓库"');
    expect(app).toContain('更改位置');
    expect(app).toContain('本地 LLM 安装向导');
    expect(app).toContain('Ollama');
    expect(app).toContain('LM Studio');
    expect(app).toContain('测试结构化整理');
    expect(app).toContain('上次刷新');
    expect(app).toContain("permissionKind === 'macos-accessibility'");
    expect(app).toContain('Windows Raw Input');
    expect(app).toContain('Defender 已隔离 WinKeyServer.exe 时不要恢复');
    expect(app).toContain('V2TKeyboardListener.exe');
    expect(app).not.toContain('className=\"mode-switch\"');
    expect(app).toContain('单独的私有仓库');
    expect(app).toContain('settings.json、lexicon.json、lexicon/*.txt、prompts/natural.md、prompts/structured.md');
    expect(app).toContain('autoCapitalize="off"');
    expect(app).toContain('autoCorrect="off"');
    expect(app).toContain('spellCheck={false}');
    expect(app).not.toContain('showAdvanced');
    expect(app).not.toContain('收起高级设置');

    const styles = await readFile(new URL('../src/renderer/styles.css', import.meta.url), 'utf8');
    expect(styles).toContain('.setting-check input[type="checkbox"]');
    expect(styles).toContain('width: 16px');
    expect(styles).toContain('.comparison-panel');
    expect(styles).toContain('overflow-x: auto');
    expect(styles).toContain('.asr-management-table');
    expect(styles).toContain('.action-strip');
    expect(styles).toContain('white-space: nowrap');
    expect(styles).toContain('.comparison-table-scroll');
    expect(styles).toContain('.resource-cell');
    expect(styles).toContain('.engine-badge');
    expect(styles).toContain('.cloud-model-toolbar');
    expect(styles).toContain('.asr-package-row');
    expect(styles).toContain('.package-progress');
    expect(styles).toContain('.cloud-model-tags');
    expect(styles).toContain('.cloud-empty-state');
    expect(styles).toContain('.doubao-comparison');
    expect(styles).toContain('.recording-overlay-compact');
    expect(styles).toContain('.usage-table');
    expect(styles).toContain('.stat-card');
    expect(styles).toContain('.model-row-actions');
    expect(styles).toContain('.llm-engine-grid');
    expect(styles).toContain('.subpage-tabs');
    expect(styles).toContain('.cloud-model-card');
    expect(styles).toContain('.cloud-model-workspace');
    expect(styles).toContain('.cloud-test-summary');
    expect(styles).toContain('.cloud-paid-hidden-notice');
    expect(styles).toContain('.cloud-model-list-rows');
    expect(styles).toContain('--font-meta');
    expect(styles).toContain('--font-body');
    expect(styles).toContain('--control-height');
    expect(styles).toContain('--control-height-compact');
    expect(styles).toContain('--radius-control');
    expect(styles).toContain('--space-3');
    expect(styles).toContain('.version-list');
    expect(styles).toContain('.ui-meta');
    expect(styles).not.toContain('min-width: 1120px');
    expect(styles).toContain('.row-check input[type="checkbox"]');
    expect(styles).toContain('.voice-options');
    expect(styles).toContain('.lexicon-trial-result');
    expect(styles).toContain('.lexicon-text-grid');
    expect(styles).toContain('.lexicon-text-editor');
    expect(styles).toContain('.recording-limit-inline');
    expect(styles).toContain('.natural-asr-recommendation');
    expect(styles).toContain('.asr-model-tags');
    expect(styles).toContain('.engine-card.active span');
    expect(styles).toContain('.local-llm-suggestions');

    const design = await readFile(new URL('../DESIGN.md', import.meta.url), 'utf8');
    expect(design).toContain('V2T Design Guidelines');
    expect(design).toContain('整表横向滚动');
  });
});
